// SPDX-License-Identifier: AGPL-3.0-or-later
// UNAUDITED. Do not use in production without a full audit.
pragma solidity ^0.8.24;

/// @title  IBondDepository
/// @notice Sells HOODZ at a discount for reserve/liquidity tokens through auto-adjusting markets.
/// @dev    UNAUDITED. Do not use in production without a full audit.
///         markets() matches the public getter generated by a `Market[] public markets` array,
///         so an implementation only has to declare that array to satisfy this interface.
interface IBondDepository {
    /// @notice Buy a bond from market id_, paying in that market quote token.
    /// @param id_        Market id.
    /// @param amount_    Amount of quote token paid in, in the quote token own decimals.
    /// @param maxPrice_  Maximum acceptable price, reverts above it (slippage guard).
    /// @param user_      Recipient of the bond payout.
    /// @param referral_  Front-end operator credited with the referral fee.
    /// @return payout_ HOODZ owed to the user, 9 decimals.
    /// @return expiry_ Timestamp at which the payout becomes fully redeemable.
    /// @return index_  Index of the created note in the user note list.
    function deposit(uint256 id_, uint256 amount_, uint256 maxPrice_, address user_, address referral_)
        external
        returns (uint256 payout_, uint256 expiry_, uint256 index_);

    /// @notice State of a bond market.
    /// @param id_ Market id.
    /// @return capacity        Remaining capacity, in HOODZ or in quote token (see capacityInQuote).
    /// @return quoteToken      Token accepted as payment.
    /// @return capacityInQuote True when capacity is denominated in the quote token.
    /// @return totalDebt       Total debt outstanding for the market.
    /// @return maxPayout       Maximum payout available in a single deposit interval.
    /// @return sold            HOODZ paid out so far by this market.
    /// @return purchased       Quote tokens taken in so far by this market.
    function markets(uint256 id_)
        external
        view
        returns (
            uint256 capacity,
            address quoteToken,
            bool capacityInQuote,
            uint64 totalDebt,
            uint64 maxPayout,
            uint64 sold,
            uint256 purchased
        );

    /// @notice Current price of a market, in quote token per HOODZ.
    /// @param id_ Market id.
    /// @return The market price, scaled to the market own price decimals.
    function marketPrice(uint256 id_) external view returns (uint256);

    /// @notice HOODZ payout for a given amount of quote token at the current price.
    /// @param amount_ Amount of quote token, in the quote token own decimals.
    /// @param id_     Market id.
    /// @return The payout in HOODZ, 9 decimals.
    function payoutFor(uint256 amount_, uint256 id_) external view returns (uint256);
}
