// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.24;

/// @dev UNAUDITED. Do not use in production without a full audit.

import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";

/// @title  Verify
/// @author Hoodz DAO
/// @notice Blockscout verification helper. Reads the manifest written by `Deploy.s.sol`
///         (`deployments/<chainid>.json`) and prints one ready-to-paste `forge verify-contract`
///         invocation per deployed contract, constructor arguments included.
/// @dev    Nothing is broadcast. Run it, then paste the printed commands:
///
///   forge script script/Verify.s.sol:Verify --rpc-url robinhood -vv
///
///         Robinhood Chain runs Blockscout, which is Etherscan-API compatible. The canonical
///         invocation for a single contract is:
///
///   forge verify-contract <ADDRESS> src/tokens/sHOOD.sol:sHOOD \
///     --chain-id 4663 \
///     --verifier blockscout \
///     --verifier-url https://robinhoodchain.blockscout.com/api \
///     --compiler-version 0.8.24 \
///     --num-of-optimizations 200 \
///     --constructor-args 0x<abi-encoded-args> \
///     --watch
///
///         Testnet is the same with `--chain-id 46630` and
///         `--verifier-url https://testnet.robinhoodchain.blockscout.com/api`.
///
///         Constructor args can also be regenerated by hand, e.g.
///
///   cast abi-encode "constructor(address)" 0xAuthority
///
///         The compiler settings MUST match foundry.toml exactly - solc 0.8.24, optimizer on,
///         200 runs, evm_version cancun, bytecode_hash none - or the bytecode will not match.
///         Blockscout accepts any non-empty API key; `export BLOCKSCOUT_API_KEY=blockscout`.
contract Verify is Script {
    /// @notice Blockscout API endpoint for Robinhood Chain mainnet.
    string public constant MAINNET_VERIFIER_URL = "https://robinhoodchain.blockscout.com/api";
    /// @notice Blockscout API endpoint for Robinhood Chain testnet.
    string public constant TESTNET_VERIFIER_URL = "https://testnet.robinhoodchain.blockscout.com/api";
    /// @notice Compiler version pinned in foundry.toml.
    string public constant COMPILER_VERSION = "0.8.24";
    /// @notice Optimizer runs pinned in foundry.toml.
    string public constant OPTIMIZER_RUNS = "200";

    /// @notice Thrown when there is no manifest for the active chain.
    /// @param path The path that was looked for.
    error ManifestNotFound(string path);

    string internal manifest;
    string internal verifierUrl;

    /// @notice Prints a `forge verify-contract` command for every entry in the deploy manifest.
    function run() public {
        string memory path = string.concat("deployments/", vm.toString(block.chainid), ".json");
        if (!vm.exists(path)) revert ManifestNotFound(path);

        manifest = vm.readFile(path);
        verifierUrl = block.chainid == 4663 ? MAINNET_VERIFIER_URL : TESTNET_VERIFIER_URL;

        console2.log("# Hoodz DAO - Blockscout verification commands");
        console2.log("# manifest:", path);
        console2.log("# chain-id:", block.chainid);
        console2.log("");

        _print("HoodzAuthority", "src/HoodzAuthority.sol:HoodzAuthority");
        // HOOD is deployed and verified by PONS, not by this repo - nothing to submit here.
        _print("sHOOD", "src/tokens/sHOOD.sol:sHOOD");
        _print("gHOOD", "src/tokens/gHOOD.sol:gHOOD");
        _print("HoodzTreasury", "src/HoodzTreasury.sol:HoodzTreasury");
        _print("HoodzBondingCalculator", "src/HoodzBondingCalculator.sol:HoodzBondingCalculator");
        _print("HoodzStaking", "src/HoodzStaking.sol:HoodzStaking");
        _print("Distributor", "src/policies/Distributor.sol:Distributor");
        _print("BondDepository", "src/policies/BondDepository.sol:BondDepository");
        _print("EmissionsManager", "src/policies/EmissionsManager.sol:EmissionsManager");
        _print("YieldRepurchaseFacility", "src/policies/YieldRepurchaseFacility.sol:YieldRepurchaseFacility");
        _print("CoolerFactory", "src/loans/CoolerFactory.sol:CoolerFactory");
        _print("Clearinghouse", "src/loans/Clearinghouse.sol:Clearinghouse");
        _print("HoodzTimelock", "src/governance/HoodzTimelock.sol:HoodzTimelock");
        _print("HoodzGovernor", "src/governance/HoodzGovernor.sol:HoodzGovernor");
        _print("PonsLaunchConfig", "src/pons/PonsLaunchConfig.sol:PonsLaunchConfig");
        _print("HoodzLaunchGuard", "src/pons/HoodzLaunchGuard.sol:HoodzLaunchGuard");
        _print("FeeRouterBuyback", "src/pons/FeeRouterBuyback.sol:FeeRouterBuyback");

        console2.log("# Cooler escrows are EIP-1167 clones of the implementation the factory deployed;");
        console2.log("# verify src/loans/Cooler.sol once at CoolerFactory.coolerImplementation().");
        console2.log("# Add --watch to any command to block until Blockscout reports the result.");
    }

    /// @dev Emits one verification command, or a skip note when the manifest has no such entry.
    /// @param name Manifest key, e.g. "HOOD".
    /// @param target `path/to/File.sol:ContractName` as forge expects it.
    function _print(string memory name, string memory target) internal view {
        address addr = _address(name);
        if (addr == address(0)) {
            console2.log(string.concat("# skip ", name, ": not present in the manifest"));
            console2.log("");
            return;
        }

        string memory cmd = string.concat(
            "forge verify-contract ",
            vm.toString(addr),
            " ",
            target,
            " --chain-id ",
            vm.toString(block.chainid),
            " --verifier blockscout --verifier-url ",
            verifierUrl,
            " --compiler-version ",
            COMPILER_VERSION,
            " --num-of-optimizations ",
            OPTIMIZER_RUNS
        );

        bytes memory args = _ctorArgs(name);
        if (args.length != 0) {
            cmd = string.concat(cmd, " --constructor-args ", vm.toString(args));
        }

        console2.log(cmd);
        console2.log("");
    }

    /// @dev Reads `.<name>` from the manifest, tolerating a missing key.
    function _address(string memory name) internal view returns (address) {
        string memory key = string.concat(".", name);
        if (!vm.keyExistsJson(manifest, key)) return address(0);
        return vm.parseJsonAddress(manifest, key);
    }

    /// @dev Reads `.constructorArgs.<name>` from the manifest, tolerating a missing key.
    function _ctorArgs(string memory name) internal view returns (bytes memory) {
        string memory key = string.concat(".constructorArgs.", name);
        if (!vm.keyExistsJson(manifest, key)) return "";
        return vm.parseJsonBytes(manifest, key);
    }
}
